// Generated by tools/generate_compatibility.py. Do not edit by hand.
#pragma once
#include <cstddef>
#include <cstdint>
namespace dolly { namespace reviewed {
struct CodeSpan { std::uintptr_t rva; std::size_t size; };
struct NamedRva { const char* name; std::uintptr_t rva; };
namespace Preload {
inline constexpr char CLIENT_SHA256[] = "678aec94adb44623e335ee7ec76c08f4477a0ea88a85cea5cb70abace1bacaa8";
inline constexpr char RESOURCE_SHA256[] = "4921031042cd2135039b4431b01bea414387b37e7f33e852e4e977f6cf1544f3";
inline constexpr std::uintptr_t MANAGER = 0x318d960;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x2657288;
inline constexpr std::uintptr_t RESOURCE_GLOBAL = 0x3de1320;
inline constexpr std::uintptr_t RESOURCE_VTABLE = 0x6bc58;
inline constexpr std::uintptr_t RESOURCE_QUERY = 0x1c860;
inline constexpr std::uintptr_t INTRO_GLOBAL = 0x3c3fda8;
inline constexpr std::uintptr_t INTRO_VTABLE = 0x2aea748;
inline constexpr CodeSpan CLIENT_CODE_SPANS[] = {{0x5f19c0, 8}, {0x5fac60, 126}, {0x1cecc60, 266}, {0x5e2bee, 51}, {0x5fe000, 10}, {0x5d7270, 75}, {0x1ab3915, 101}, {0x1acffe0, 230}, {0x1af5ebe, 465}, {0x1ade7c0, 66}, {0x1abba80, 554}};
inline constexpr std::uintptr_t MANAGER_SIZE = 0x40;
inline constexpr std::uintptr_t COMPLETED = 0x24;
inline constexpr std::uintptr_t RESOURCE = 0x30;
inline constexpr std::uintptr_t JOB = 0x38;
inline constexpr std::uintptr_t LIFECYCLE_BEGIN = 0x3c;
inline constexpr std::uintptr_t LIFECYCLE_END = 0x3e;
inline constexpr std::uintptr_t RESOURCE_QUERY_SLOT = 0xc0;
inline constexpr std::uintptr_t RESOURCE_DONE = 0x44;
inline constexpr std::uintptr_t INTRO_SIZE = 0x84;
inline constexpr std::uintptr_t INTRO_PHASE = 0x80;
}
namespace ReplayCamera {
inline constexpr char CLIENT_SHA256[] = "678aec94adb44623e335ee7ec76c08f4477a0ea88a85cea5cb70abace1bacaa8";
inline constexpr std::uintptr_t MANAGER = 0x3642ef0;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x2650b90;
inline constexpr std::uintptr_t GAMEPLAY_CAMERA_VTABLE = 0x26585f8;
inline constexpr std::uintptr_t RULES_GLOBAL = 0x3c23060;
inline constexpr std::uintptr_t RULES_VTABLE = 0x268cd28;
inline constexpr CodeSpan CODE_SPANS[] = {{0x5d3c30, 685}, {0x5b6230, 181}, {0x180ccb0, 261}, {0x1821cf0, 5}, {0x1825e10, 6}, {0x1b0dba0, 1642}, {0x18b0c70, 88}, {0x1abd760, 17}, {0x1aefb91, 112}, {0x1b073d0, 91}, {0x1b0d850, 118}};
inline constexpr std::uintptr_t RULES_STATE = 0x74;
inline constexpr std::uintptr_t MANAGER_SIZE = 0x48;
inline constexpr std::uintptr_t CURRENT_CAMERA = 0x28;
inline constexpr std::uintptr_t BLENDING = 0x38;
inline constexpr std::uintptr_t BLEND_WEIGHT = 0x44;
inline constexpr std::uintptr_t HUD_ROOT = 0x3c3f1c0;
inline constexpr std::uintptr_t HUD_ROOT_VTABLE = 0x2ae69b0;
inline constexpr std::uintptr_t HUD_TAKEOVER_COUNT = 0x284;
}
namespace FollowCapabilities {
inline constexpr char TIER0_SHA256[] = "6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332";
inline constexpr CodeSpan CLIENT_SPANS[] = {{0x8f0b0, 3430}, {0x90b00, 166}, {0x233950, 115}, {0x23d4160, 129}, {0x251280, 10}, {0x609d46, 11}};
inline constexpr CodeSpan TIER0_SPANS[] = {{0x20fd40, 633}};
inline constexpr NamedRva REFS[] = {{"pivot_x_offset", 0x3644940}, {"pivot_y_offset", 0x3644950}, {"pivot_z_offset", 0x3644960}, {"pivot_x_offset_crouching", 0x3644970}, {"pivot_y_offset_crouching", 0x3644980}, {"pivot_z_offset_crouching", 0x3644990}, {"x_offset", 0x36449a0}, {"y_offset", 0x36449b0}, {"z_offset", 0x36449c0}, {"x_worst_case_offset", 0x36449d0}, {"y_worst_case_offset", 0x36449e0}, {"z_worst_case_offset", 0x36449f0}, {"ads_x_offset", 0x3644a00}, {"ads_y_offset", 0x3644a10}, {"ads_z_offset", 0x3644a20}, {"fov", 0x3644a30}, {"ads_fov", 0x3644a40}};
inline constexpr CodeSpan OWN_HEALTH_SPANS[] = {{0x1b8e00, 174}, {0x1afa3c0, 803}, {0x1adc550, 47}};
inline constexpr std::uintptr_t ENABLED_REF = 0x3644930;
inline constexpr std::uintptr_t FOLLOW_AIM_REF = 0x3644668;
inline constexpr std::uintptr_t OWN_HEALTH_REF = 0x3c3fb18;
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x415b000;
inline constexpr std::uintptr_t TIER0_IMAGE_SIZE = 0x401000;
inline constexpr std::uintptr_t CVAR_DATA_SIZE = 0x5c;
inline constexpr std::uintptr_t CVAR_TYPE = 0x28;
inline constexpr std::uintptr_t CVAR_FLAGS = 0x30;
inline constexpr std::uintptr_t CVAR_VALUE = 0x58;
}
namespace FollowTarget {
inline constexpr CodeSpan TARGET_SPANS[] = {{0x1619af0, 121}, {0x866eb0, 5}, {0x866ec0, 92}, {0x838550, 193}, {0x8181c0, 17}, {0x8181e0, 17}};
inline constexpr CodeSpan HEALTH_CONTEXT_SPANS[] = {{0x934240, 33}, {0x1619ad0, 23}, {0x57bbe0, 252}, {0x8181c0, 17}, {0x8181e0, 17}, {0x866f50, 137}, {0x1b3d5e0, 297}, {0x1b3dc30, 65}, {0x816bb0, 55}, {0x4a5170, 5}, {0x70be60, 3}, {0x15f5a50, 3}, {0x52e750, 3}, {0x589c46, 3}, {0x8507d0, 380}};
inline constexpr std::uintptr_t CONTROLLER_VTABLE = 0x26b7958;
inline constexpr std::uintptr_t OBSERVER_PAWN_VTABLE = 0x2634338;
inline constexpr std::uintptr_t PLAYER_PAWN_VTABLE = 0x2640ea8;
inline constexpr std::uintptr_t FAMILIAR_CLONE_PAWN_VTABLE = 0x27ee740;
inline constexpr std::uintptr_t SERVICES_VTABLES[] = {0x26b83a0, 0x2a5a4a8};
inline constexpr std::uintptr_t CONTROLLER_FINAL_VTABLE = 0x26b7928;
inline constexpr std::uintptr_t OBSERVER_SERVICES_OFFSET = 0xe98;
inline constexpr std::uintptr_t ENTITY_LIST = 0x34309b8;
inline constexpr std::uintptr_t CONTROLLER = 0x3bdc430;
inline constexpr std::uintptr_t OBSERVER_PREDICATE = 0x52e750;
inline constexpr std::uintptr_t GET_OBSERVER_MODE = 0x866eb0;
inline constexpr std::uintptr_t GET_OBSERVER_TARGET = 0x866ec0;
inline constexpr std::uintptr_t PLAYER_PREDICATE = 0x15f5a50;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE = 0x589de0;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE = 0x70be60;
inline constexpr std::uintptr_t IDENTITY_STRIDE = 0x70;
inline constexpr std::uintptr_t IDENTITY_HANDLE = 0x10;
inline constexpr std::uintptr_t ENTITY_IDENTITY = 0x10;
inline constexpr std::uintptr_t CONTROLLER_PAWN = 0x6bc;
inline constexpr std::uintptr_t NETWORK_STATE = 0x3ef;
inline constexpr std::uintptr_t OBSERVER_PREDICATE_SLOT = 0x500;
inline constexpr std::uintptr_t OBSERVER_MODE_SLOT = 0xf0;
inline constexpr std::uintptr_t OBSERVER_TARGET_SLOT = 0x100;
inline constexpr std::uintptr_t OBSERVER_MODE = 0x48;
inline constexpr std::uintptr_t OBSERVER_TARGET = 0x4c;
inline constexpr std::uintptr_t PLAYER_PREDICATE_SLOT = 0x4e0;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE_SLOT = 0xad8;
inline constexpr std::uintptr_t PAWN_CONTROLLER = 0x51c;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE_SLOT = 0x4e8;
inline constexpr std::uintptr_t CONTROLLER_FINAL_DATA = 0x908;
}
namespace AttachRuntime {
inline constexpr char CLIENT_SHA256[] = "678aec94adb44623e335ee7ec76c08f4477a0ea88a85cea5cb70abace1bacaa8";
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x415b000;
inline constexpr std::uintptr_t INITIALIZER = 0x20381b0;
inline constexpr std::uintptr_t ENTITY_VTABLE = 0x2a48f10;
inline constexpr std::uintptr_t ENTITY_GLOBAL = 0x3d5dd00;
inline constexpr unsigned char INITIALIZER_BYTES[] = {0xf, 0xb6, 0x44, 0x24, 0x28, 0x88, 0x44, 0x24, 0x28, 0x48, 0x89, 0xd, 0x40, 0x5b, 0xd2, 0x1, 0xe9, 0x9b, 0xbf, 0xff, 0xff};
}
enum class AttachFieldIndex : unsigned { scene_node, owner, player_origin, player_angles, eye_offset, eye_angles, scene_child, scene_sibling };
inline constexpr std::size_t kViewOffsetComponents[] = {16, 24, 32};
} } // namespace dolly::reviewed
