// Generated by tools/generate_compatibility.py. Do not edit by hand.
#pragma once
#include <cstddef>
#include <cstdint>
namespace dolly { namespace reviewed {
struct CodeSpan { std::uintptr_t rva; std::size_t size; };
struct NamedRva { const char* name; std::uintptr_t rva; };
namespace Preload {
inline constexpr char CLIENT_SHA256[] = "e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0";
inline constexpr char RESOURCE_SHA256[] = "4921031042cd2135039b4431b01bea414387b37e7f33e852e4e977f6cf1544f3";
inline constexpr std::uintptr_t MANAGER = 0x31cca40;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x2687ee8;
inline constexpr std::uintptr_t RESOURCE_GLOBAL = 0x3e37fc0;
inline constexpr std::uintptr_t RESOURCE_VTABLE = 0x6bc58;
inline constexpr std::uintptr_t RESOURCE_QUERY = 0x1c860;
inline constexpr std::uintptr_t INTRO_GLOBAL = 0x3c96a28;
inline constexpr std::uintptr_t INTRO_VTABLE = 0x2b24ae8;
inline constexpr CodeSpan CLIENT_CODE_SPANS[] = {{0x5f2b50, 8}, {0x5fbdf0, 126}, {0x1d1cdf0, 266}, {0x5e3d7e, 51}, {0x5ff190, 10}, {0x5d8400, 75}, {0x1ae4cd5, 101}, {0x1b014a0, 230}, {0x1b2744e, 465}, {0x1b0fcb0, 66}, {0x1aecf40, 554}};
inline constexpr std::uintptr_t MANAGER_SIZE = 0x40;
inline constexpr std::uintptr_t COMPLETED = 0x24;
inline constexpr std::uintptr_t RESOURCE = 0x30;
inline constexpr std::uintptr_t JOB = 0x38;
inline constexpr std::uintptr_t LIFECYCLE_BEGIN = 0x3c;
inline constexpr std::uintptr_t LIFECYCLE_END = 0x3e;
inline constexpr std::uintptr_t RESOURCE_QUERY_SLOT = 0xc0;
inline constexpr std::uintptr_t RESOURCE_DONE = 0x44;
inline constexpr std::uintptr_t INTRO_SIZE = 0x84;
inline constexpr std::uintptr_t INTRO_PHASE = 0x80;
}
namespace ReplayCamera {
inline constexpr char CLIENT_SHA256[] = "e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0";
inline constexpr std::uintptr_t MANAGER = 0x3686a70;
inline constexpr std::uintptr_t MANAGER_VTABLE = 0x26816a0;
inline constexpr std::uintptr_t GAMEPLAY_CAMERA_VTABLE = 0x26890e8;
inline constexpr std::uintptr_t RULES_GLOBAL = 0x3c79e60;
inline constexpr std::uintptr_t RULES_VTABLE = 0x26bd888;
inline constexpr CodeSpan CODE_SPANS[] = {{0x5d4e00, 685}, {0x5b79e0, 181}, {0x1841c00, 261}, {0x1856c40, 5}, {0x185ad60, 6}, {0x1b3f150, 1642}, {0x18e5dc0, 88}, {0x1aeec20, 17}, {0x1b21119, 112}, {0x1b38980, 91}, {0x1b3ee00, 118}};
inline constexpr std::uintptr_t RULES_STATE = 0x74;
inline constexpr std::uintptr_t MANAGER_SIZE = 0x48;
inline constexpr std::uintptr_t CURRENT_CAMERA = 0x28;
inline constexpr std::uintptr_t BLENDING = 0x38;
inline constexpr std::uintptr_t BLEND_WEIGHT = 0x44;
inline constexpr std::uintptr_t HUD_ROOT = 0x3c95e48;
inline constexpr std::uintptr_t HUD_ROOT_VTABLE = 0x2b20d08;
inline constexpr std::uintptr_t HUD_TAKEOVER_COUNT = 0x284;
}
namespace FollowCapabilities {
inline constexpr char TIER0_SHA256[] = "6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332";
inline constexpr CodeSpan CLIENT_SPANS[] = {{0x8f030, 3430}, {0x90780, 166}, {0x234d90, 115}, {0x2404c70, 129}, {0x2526c0, 10}, {0x60aed6, 11}};
inline constexpr CodeSpan TIER0_SPANS[] = {{0x20fd40, 633}};
inline constexpr NamedRva REFS[] = {{"pivot_x_offset", 0x36884d0}, {"pivot_y_offset", 0x36884e0}, {"pivot_z_offset", 0x36884f0}, {"pivot_x_offset_crouching", 0x3688500}, {"pivot_y_offset_crouching", 0x3688510}, {"pivot_z_offset_crouching", 0x3688520}, {"x_offset", 0x3688530}, {"y_offset", 0x3688540}, {"z_offset", 0x3688550}, {"x_worst_case_offset", 0x3688560}, {"y_worst_case_offset", 0x3688570}, {"z_worst_case_offset", 0x3688580}, {"ads_x_offset", 0x3688590}, {"ads_y_offset", 0x36885a0}, {"ads_z_offset", 0x36885b0}, {"fov", 0x36885c0}, {"ads_fov", 0x36885d0}};
inline constexpr CodeSpan OWN_HEALTH_SPANS[] = {{0x1ba210, 174}, {0x1b2b950, 803}, {0x1b0da10, 47}};
inline constexpr std::uintptr_t ENABLED_REF = 0x36884c0;
inline constexpr std::uintptr_t FOLLOW_AIM_REF = 0x36881f8;
inline constexpr std::uintptr_t OWN_HEALTH_REF = 0x3c96798;
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x41b6000;
inline constexpr std::uintptr_t TIER0_IMAGE_SIZE = 0x401000;
inline constexpr std::uintptr_t CVAR_DATA_SIZE = 0x5c;
inline constexpr std::uintptr_t CVAR_TYPE = 0x28;
inline constexpr std::uintptr_t CVAR_FLAGS = 0x30;
inline constexpr std::uintptr_t CVAR_VALUE = 0x58;
}
namespace FollowTarget {
inline constexpr CodeSpan TARGET_SPANS[] = {{0x164edd0, 121}, {0x868350, 5}, {0x868360, 92}, {0x839150, 193}, {0x819360, 17}, {0x819380, 17}};
inline constexpr CodeSpan HEALTH_CONTEXT_SPANS[] = {{0x9370b0, 33}, {0x164edb0, 23}, {0x57d580, 252}, {0x819360, 17}, {0x819380, 17}, {0x8683f0, 137}, {0x1b6e960, 297}, {0x1b6efb0, 65}, {0x817d50, 55}, {0x4a6e90, 5}, {0x70d0b0, 3}, {0x162ad00, 3}, {0x530be0, 3}, {0x58b5e6, 3}, {0x8515c0, 380}};
inline constexpr std::uintptr_t CONTROLLER_VTABLE = 0x26e7fc8;
inline constexpr std::uintptr_t OBSERVER_PAWN_VTABLE = 0x2664fa0;
inline constexpr std::uintptr_t PLAYER_PAWN_VTABLE = 0x2671a10;
inline constexpr std::uintptr_t FAMILIAR_CLONE_PAWN_VTABLE = 0x2829ac0;
inline constexpr std::uintptr_t SERVICES_VTABLES[] = {0x26e8a10, 0x2a951b8};
inline constexpr std::uintptr_t CONTROLLER_FINAL_VTABLE = 0x26e7f98;
inline constexpr std::uintptr_t OBSERVER_SERVICES_OFFSET = 0xe98;
inline constexpr std::uintptr_t ENTITY_LIST = 0x3474738;
inline constexpr std::uintptr_t CONTROLLER = 0x3c33230;
inline constexpr std::uintptr_t OBSERVER_PREDICATE = 0x530be0;
inline constexpr std::uintptr_t GET_OBSERVER_MODE = 0x868350;
inline constexpr std::uintptr_t GET_OBSERVER_TARGET = 0x868360;
inline constexpr std::uintptr_t PLAYER_PREDICATE = 0x162ad00;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE = 0x58b780;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE = 0x70d0b0;
inline constexpr std::uintptr_t IDENTITY_STRIDE = 0x70;
inline constexpr std::uintptr_t IDENTITY_HANDLE = 0x10;
inline constexpr std::uintptr_t ENTITY_IDENTITY = 0x10;
inline constexpr std::uintptr_t CONTROLLER_PAWN = 0x6bc;
inline constexpr std::uintptr_t NETWORK_STATE = 0x3ef;
inline constexpr std::uintptr_t OBSERVER_PREDICATE_SLOT = 0x500;
inline constexpr std::uintptr_t OBSERVER_MODE_SLOT = 0xf0;
inline constexpr std::uintptr_t OBSERVER_TARGET_SLOT = 0x100;
inline constexpr std::uintptr_t OBSERVER_MODE = 0x48;
inline constexpr std::uintptr_t OBSERVER_TARGET = 0x4c;
inline constexpr std::uintptr_t PLAYER_PREDICATE_SLOT = 0x4e0;
inline constexpr std::uintptr_t PLAYER_DATA_PREDICATE_SLOT = 0xad8;
inline constexpr std::uintptr_t PAWN_CONTROLLER = 0x51c;
inline constexpr std::uintptr_t CONTROLLER_PREDICATE_SLOT = 0x4e8;
inline constexpr std::uintptr_t CONTROLLER_FINAL_DATA = 0x908;
}
namespace AttachRuntime {
inline constexpr char CLIENT_SHA256[] = "e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0";
inline constexpr std::uintptr_t CLIENT_IMAGE_SIZE = 0x41b6000;
inline constexpr std::uintptr_t INITIALIZER = 0x2067ff0;
inline constexpr std::uintptr_t ENTITY_VTABLE = 0x2a83c20;
inline constexpr std::uintptr_t ENTITY_GLOBAL = 0x3db49b0;
inline constexpr unsigned char INITIALIZER_BYTES[] = {0xf, 0xb6, 0x44, 0x24, 0x28, 0x88, 0x44, 0x24, 0x28, 0x48, 0x89, 0xd, 0xb0, 0xc9, 0xd4, 0x1, 0xe9, 0x9b, 0xbf, 0xff, 0xff};
}
enum class AttachFieldIndex : unsigned { scene_node, owner, player_origin, player_angles, eye_offset, eye_angles, scene_child, scene_sibling };
inline constexpr std::size_t kViewOffsetComponents[] = {16, 24, 32};
} } // namespace dolly::reviewed
