"""Generated by tools/generate_compatibility.py; edit reviewed profiles, not this file."""

class Preload:
    CLIENT_SHA256 = 'efb29f4a92516539c509aecd1988db3051b2ada03e5fefed338c84568b835b6b'
    RESOURCE_SHA256 = '4921031042cd2135039b4431b01bea414387b37e7f33e852e4e977f6cf1544f3'
    MANAGER = 52222576
    MANAGER_VTABLE = 40406776
    RESOURCE_GLOBAL = 65245120
    RESOURCE_VTABLE = 441432
    RESOURCE_QUERY = 116832
    INTRO_GLOBAL = 63535656
    INTRO_VTABLE = 45242984
    CLIENT_CODE_SPANS = ((6236864, 8), (6274400, 126), (30530016, 266), (6175982, 51), (6287616, 10), (6128496, 75), (28203253, 101), (28319936, 230), (28475454, 465), (28379344, 66), (28236640, 554))
    MANAGER_SIZE = 64
    COMPLETED = 36
    RESOURCE = 48
    JOB = 56
    LIFECYCLE_BEGIN = 60
    LIFECYCLE_END = 62
    RESOURCE_QUERY_SLOT = 192
    RESOURCE_DONE = 68
    INTRO_SIZE = 132
    INTRO_PHASE = 128


class ReplayCamera:
    CLIENT_SHA256 = 'efb29f4a92516539c509aecd1988db3051b2ada03e5fefed338c84568b835b6b'
    MANAGER = 57179120
    MANAGER_VTABLE = 40380080
    GAMEPLAY_CAMERA_VTABLE = 40411384
    RULES_GLOBAL = 63417952
    RULES_VTABLE = 40626328
    CODE_SPANS = ((6114672, 685), (5994832, 181), (25438240, 261), (25524320, 5), (25540992, 6), (28572992, 1642), (26110432, 88), (28244032, 17), (28450073, 112), (28546416, 91), (28572144, 118))
    RULES_STATE = 116
    MANAGER_SIZE = 72
    CURRENT_CAMERA = 40
    BLENDING = 56
    BLEND_WEIGHT = 68
    HUD_ROOT = 63532616
    HUD_ROOT_VTABLE = 45227152
    HUD_TAKEOVER_COUNT = 644


class FollowCapabilities:
    TIER0_SHA256 = '6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332'
    CLIENT_SPANS = ((585776, 3430), (591744, 166), (2313616, 115), (37771360, 129), (2434752, 10), (6336070, 11))
    TIER0_SPANS = ((2161984, 633),)
    REFS = {'pivot_x_offset': 57185872, 'pivot_y_offset': 57185888, 'pivot_z_offset': 57185904, 'pivot_x_offset_crouching': 57185920, 'pivot_y_offset_crouching': 57185936, 'pivot_z_offset_crouching': 57185952, 'x_offset': 57185968, 'y_offset': 57185984, 'z_offset': 57186000, 'x_worst_case_offset': 57186016, 'y_worst_case_offset': 57186032, 'z_worst_case_offset': 57186048, 'ads_x_offset': 57186064, 'ads_y_offset': 57186080, 'ads_z_offset': 57186096, 'fov': 57186112, 'ads_fov': 57186128}
    OWN_HEALTH_SPANS = ((1810960, 174), (28493120, 803), (28370480, 47))
    ENABLED_REF = 57185856
    FOLLOW_AIM_REF = 57185144
    OWN_HEALTH_REF = 63535000
    CLIENT_IMAGE_SIZE = 68907008
    TIER0_IMAGE_SIZE = 4198400
    CVAR_DATA_SIZE = 92
    CVAR_TYPE = 40
    CVAR_FLAGS = 48
    CVAR_VALUE = 88


class FollowTarget:
    TARGET_SPANS = ((23394800, 121), (8815296, 5), (8815312, 92), (8622272, 193), (8491728, 17), (8491760, 17))
    HEALTH_CONTEXT_SPANS = ((9661936, 33), (23394768, 23), (5756144, 252), (8491728, 17), (8491760, 17), (8815456, 137), (28767568, 297), (28769184, 65), (8486080, 55), (4877824, 5), (7393312, 3), (23014613, 3), (5442384, 3), (5813590, 3), (8721712, 380))
    CONTROLLER_VTABLE = 40800216
    OBSERVER_PAWN_VTABLE = 40263616
    PLAYER_PAWN_VTABLE = 40315424
    FAMILIAR_CLONE_PAWN_VTABLE = 42117872
    SERVICES_VTABLES = (40802848, 44654920)
    CONTROLLER_FINAL_VTABLE = 40800168
    OBSERVER_SERVICES_OFFSET = 3736
    ENTITY_LIST = 55007416
    CONTROLLER = 63128176
    OBSERVER_PREDICATE = 5442384
    GET_OBSERVER_MODE = 8815296
    GET_OBSERVER_TARGET = 8815312
    PLAYER_PREDICATE = 23014613
    PLAYER_DATA_PREDICATE = 5814000
    CONTROLLER_PREDICATE = 7393312
    IDENTITY_STRIDE = 112
    IDENTITY_HANDLE = 16
    ENTITY_IDENTITY = 16
    CONTROLLER_PAWN = 1724
    NETWORK_STATE = 1007
    OBSERVER_PREDICATE_SLOT = 1280
    OBSERVER_MODE_SLOT = 240
    OBSERVER_TARGET_SLOT = 256
    OBSERVER_MODE = 72
    OBSERVER_TARGET = 76
    PLAYER_PREDICATE_SLOT = 1248
    PLAYER_DATA_PREDICATE_SLOT = 2776
    PAWN_CONTROLLER = 1308
    CONTROLLER_PREDICATE_SLOT = 1256
    CONTROLLER_FINAL_DATA = 2312


class AttachRuntime:
    CLIENT_SHA256 = 'efb29f4a92516539c509aecd1988db3051b2ada03e5fefed338c84568b835b6b'
    CLIENT_IMAGE_SIZE = 68907008
    INITIALIZER = 33983456
    ENTITY_VTABLE = 44583856
    ENTITY_GLOBAL = 64706992
    INITIALIZER_BYTES = b'\x0f\xb6D$(\x88D$(H\x89\r\xc0\xcd\xd4\x01\xe9\x9b\xbf\xff\xff'


ATTACH_FIELD_SPECS = (('player_origin', 'CGameSceneNode', 'm_vecAbsOrigin', 'VectorWS', True), ('player_angles', 'CGameSceneNode', 'm_angAbsRotation', 'QAngle', True), ('eye_offset', 'C_BaseModelEntity', 'm_vecViewOffset', 'CNetworkViewOffsetVector', True), ('eye_angles', 'C_CitadelPlayerPawn', 'm_angEyeAngles', 'QAngle', True), ('scene_child', 'CGameSceneNode', 'm_pChild', 'CGameSceneNode*', True), ('scene_sibling', 'CGameSceneNode', 'm_pNextSibling', 'CGameSceneNode*', True), ('world_transform', 'CGameSceneNode', 'm_nodeToWorld', 'CTransformWS', False), ('attach_bone', 'CGameSceneNode', 'm_nParentAttachmentOrBone', 'int16', False), ('owner_entity', 'C_BaseEntity', 'm_hOwnerEntity', 'CHandle', False), ('pawn_controller', 'C_BasePlayerPawn', 'm_hController', 'CHandle', False))
ATTACH_WIRE_FIELDS = ('scene_node', 'owner', 'player_origin', 'player_angles', 'eye_offset', 'eye_angles', 'scene_child', 'scene_sibling')
VIEW_OFFSET_VALUE_OFFSETS = (16, 24, 32)
