"""Generated by tools/generate_compatibility.py; edit reviewed profiles, not this file."""

class Preload:
    CLIENT_SHA256 = 'e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0'
    RESOURCE_SHA256 = '4921031042cd2135039b4431b01bea414387b37e7f33e852e4e977f6cf1544f3'
    MANAGER = 52218432
    MANAGER_VTABLE = 40402664
    RESOURCE_GLOBAL = 65241024
    RESOURCE_VTABLE = 441432
    RESOURCE_QUERY = 116832
    INTRO_GLOBAL = 63531560
    INTRO_VTABLE = 45239016
    CLIENT_CODE_SPANS = ((6237008, 8), (6274544, 126), (30526960, 266), (6176126, 51), (6287760, 10), (6128640, 75), (28200149, 101), (28316832, 230), (28472398, 465), (28376240, 66), (28233536, 554))
    MANAGER_SIZE = 64
    COMPLETED = 36
    RESOURCE = 48
    JOB = 56
    LIFECYCLE_BEGIN = 60
    LIFECYCLE_END = 62
    RESOURCE_QUERY_SLOT = 192
    RESOURCE_DONE = 68
    INTRO_SIZE = 132
    INTRO_PHASE = 128


class ReplayCamera:
    CLIENT_SHA256 = 'e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0'
    MANAGER = 57174640
    MANAGER_VTABLE = 40375968
    GAMEPLAY_CAMERA_VTABLE = 40407272
    RULES_GLOBAL = 63413856
    RULES_VTABLE = 40622216
    CODE_SPANS = ((6114816, 685), (5994976, 181), (25435136, 261), (25521216, 5), (25537888, 6), (28569936, 1642), (26107328, 88), (28240928, 17), (28447001, 112), (28543360, 91), (28569088, 118))
    RULES_STATE = 116
    MANAGER_SIZE = 72
    CURRENT_CAMERA = 40
    BLENDING = 56
    BLEND_WEIGHT = 68
    HUD_ROOT = 63528520
    HUD_ROOT_VTABLE = 45223176
    HUD_TAKEOVER_COUNT = 644


class FollowCapabilities:
    TIER0_SHA256 = '6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332'
    CLIENT_SPANS = ((585776, 3430), (591744, 166), (2313616, 115), (37768304, 129), (2434752, 10), (6336214, 11))
    TIER0_SPANS = ((2161984, 633),)
    REFS = {'pivot_x_offset': 57181392, 'pivot_y_offset': 57181408, 'pivot_z_offset': 57181424, 'pivot_x_offset_crouching': 57181440, 'pivot_y_offset_crouching': 57181456, 'pivot_z_offset_crouching': 57181472, 'x_offset': 57181488, 'y_offset': 57181504, 'z_offset': 57181520, 'x_worst_case_offset': 57181536, 'y_worst_case_offset': 57181552, 'z_worst_case_offset': 57181568, 'ads_x_offset': 57181584, 'ads_y_offset': 57181600, 'ads_z_offset': 57181616, 'fov': 57181632, 'ads_fov': 57181648}
    OWN_HEALTH_SPANS = ((1810960, 174), (28490064, 803), (28367376, 47))
    ENABLED_REF = 57181376
    FOLLOW_AIM_REF = 57180664
    OWN_HEALTH_REF = 63530904
    CLIENT_IMAGE_SIZE = 68902912
    TIER0_IMAGE_SIZE = 4198400
    CVAR_DATA_SIZE = 92
    CVAR_TYPE = 40
    CVAR_FLAGS = 48
    CVAR_VALUE = 88


class FollowTarget:
    TARGET_SPANS = ((23391696, 121), (8815440, 5), (8815456, 92), (8622416, 193), (8491872, 17), (8491904, 17))
    HEALTH_CONTEXT_SPANS = ((9662640, 33), (23391664, 23), (5756288, 252), (8491872, 17), (8491904, 17), (8815600, 137), (28764512, 297), (28766128, 65), (8486224, 55), (4877968, 5), (7393456, 3), (23244032, 3), (5442528, 3), (5813734, 3), (8721856, 380))
    CONTROLLER_VTABLE = 40796104
    OBSERVER_PAWN_VTABLE = 40259488
    PLAYER_PAWN_VTABLE = 40311312
    FAMILIAR_CLONE_PAWN_VTABLE = 42113728
    SERVICES_VTABLES = (40798736, 44650936)
    CONTROLLER_FINAL_VTABLE = 40796056
    OBSERVER_SERVICES_OFFSET = 3736
    ENTITY_LIST = 55002936
    CONTROLLER = 63124016
    OBSERVER_PREDICATE = 5442528
    GET_OBSERVER_MODE = 8815440
    GET_OBSERVER_TARGET = 8815456
    PLAYER_PREDICATE = 23244032
    PLAYER_DATA_PREDICATE = 5814144
    CONTROLLER_PREDICATE = 7393456
    IDENTITY_STRIDE = 112
    IDENTITY_HANDLE = 16
    ENTITY_IDENTITY = 16
    CONTROLLER_PAWN = 1724
    NETWORK_STATE = 1007
    OBSERVER_PREDICATE_SLOT = 1280
    OBSERVER_MODE_SLOT = 240
    OBSERVER_TARGET_SLOT = 256
    OBSERVER_MODE = 72
    OBSERVER_TARGET = 76
    PLAYER_PREDICATE_SLOT = 1248
    PLAYER_DATA_PREDICATE_SLOT = 2776
    PAWN_CONTROLLER = 1308
    CONTROLLER_PREDICATE_SLOT = 1256
    CONTROLLER_FINAL_DATA = 2312


class AttachRuntime:
    CLIENT_SHA256 = 'e0edcb5f9d86f879cc9c0ba0ed37714760b81266b47abcdbea7f42ec233f82e0'
    CLIENT_IMAGE_SIZE = 68902912
    INITIALIZER = 33980400
    ENTITY_VTABLE = 44579872
    ENTITY_GLOBAL = 64702896
    INITIALIZER_BYTES = b'\x0f\xb6D$(\x88D$(H\x89\r\xb0\xc9\xd4\x01\xe9\x9b\xbf\xff\xff'


ATTACH_FIELD_SPECS = (('player_origin', 'CGameSceneNode', 'm_vecAbsOrigin', 'VectorWS', True), ('player_angles', 'CGameSceneNode', 'm_angAbsRotation', 'QAngle', True), ('eye_offset', 'C_BaseModelEntity', 'm_vecViewOffset', 'CNetworkViewOffsetVector', True), ('eye_angles', 'C_CitadelPlayerPawn', 'm_angEyeAngles', 'QAngle', True), ('scene_child', 'CGameSceneNode', 'm_pChild', 'CGameSceneNode*', True), ('scene_sibling', 'CGameSceneNode', 'm_pNextSibling', 'CGameSceneNode*', True), ('world_transform', 'CGameSceneNode', 'm_nodeToWorld', 'CTransformWS', False), ('attach_bone', 'CGameSceneNode', 'm_nParentAttachmentOrBone', 'int16', False), ('owner_entity', 'C_BaseEntity', 'm_hOwnerEntity', 'CHandle', False), ('pawn_controller', 'C_BasePlayerPawn', 'm_hController', 'CHandle', False))
ATTACH_WIRE_FIELDS = ('scene_node', 'owner', 'player_origin', 'player_angles', 'eye_offset', 'eye_angles', 'scene_child', 'scene_sibling')
VIEW_OFFSET_VALUE_OFFSETS = (16, 24, 32)
