"""Generated by tools/generate_compatibility.py; edit reviewed profiles, not this file."""

class Preload:
    CLIENT_SHA256 = '948260612c9b7243964e4a0d5f0f6252ae846ceaa6e8c0e95b83bd5eba4caf60'
    RESOURCE_SHA256 = '86d09bc988ab3609d43473c3fdc07246bd8958e7f8fc50af4bbba4ffe05a3da0'
    MANAGER = 51923088
    MANAGER_VTABLE = 40173968
    RESOURCE_GLOBAL = 64839728
    RESOURCE_VTABLE = 441432
    RESOURCE_QUERY = 116832
    INTRO_GLOBAL = 63129592
    INTRO_VTABLE = 44968104
    CLIENT_CODE_SPANS = ((6224336, 8), (6261872, 126), (30294672, 266), (6163454, 51), (6275088, 10), (6115968, 75), (27972837, 101), (28093376, 230), (28249838, 465), (28153264, 66), (28009408, 554))
    MANAGER_SIZE = 64
    COMPLETED = 36
    RESOURCE = 48
    JOB = 56
    LIFECYCLE_BEGIN = 60
    LIFECYCLE_END = 62
    RESOURCE_QUERY_SLOT = 192
    RESOURCE_DONE = 68
    INTRO_SIZE = 132
    INTRO_PHASE = 128


class ReplayCamera:
    CLIENT_SHA256 = '948260612c9b7243964e4a0d5f0f6252ae846ceaa6e8c0e95b83bd5eba4caf60'
    MANAGER = 56853680
    MANAGER_VTABLE = 40147616
    GAMEPLAY_CAMERA_VTABLE = 40178936
    RULES_GLOBAL = 63011552
    RULES_VTABLE = 40393136
    CODE_SPANS = ((6102112, 685), (5980768, 181), (25200192, 261), (25286272, 5), (25302944, 6), (28353440, 1642), (25871872, 88))
    RULES_STATE = 116
    MANAGER_SIZE = 72
    CURRENT_CAMERA = 40
    BLENDING = 56
    BLEND_WEIGHT = 68


class FollowCapabilities:
    TIER0_SHA256 = '6793cc7306ff40283ba038a784fe96f99f6d38f93c825571ee93ab6b9d9d5332'
    CLIENT_SPANS = ((585728, 3430), (592464, 166), (2306032, 115), (37542048, 129), (2427136, 10), (6323542, 11))
    TIER0_SPANS = ((2161984, 633),)
    REFS = {'pivot_x_offset': 56860400, 'pivot_y_offset': 56860416, 'pivot_z_offset': 56860432, 'pivot_x_offset_crouching': 56860448, 'pivot_y_offset_crouching': 56860464, 'pivot_z_offset_crouching': 56860480, 'x_offset': 56860496, 'y_offset': 56860512, 'z_offset': 56860528, 'x_worst_case_offset': 56860544, 'y_worst_case_offset': 56860560, 'z_worst_case_offset': 56860576, 'ads_x_offset': 56860592, 'ads_y_offset': 56860608, 'ads_z_offset': 56860624, 'fov': 56860640, 'ads_fov': 56860656}
    OWN_HEALTH_SPANS = ((1805584, 174), (28269744, 803), (28144304, 47))
    ENABLED_REF = 56860384
    FOLLOW_AIM_REF = 56859672
    OWN_HEALTH_REF = 63128952
    CLIENT_IMAGE_SIZE = 68485120
    TIER0_IMAGE_SIZE = 4198400
    CVAR_DATA_SIZE = 92
    CVAR_TYPE = 40
    CVAR_FLAGS = 48
    CVAR_VALUE = 88


class FollowTarget:
    TARGET_SPANS = ((23155680, 121), (8800976, 5), (8800992, 92), (8610416, 193), (8478432, 17), (8478464, 17))
    HEALTH_CONTEXT_SPANS = ((9636576, 33), (23155648, 23), (5741712, 252), (8478432, 17), (8478464, 17), (8801136, 137), (28551520, 297), (28553216, 65), (8472784, 55), (4863024, 5), (7380080, 3), (23008064, 3), (5425312, 3), (5799584, 3), (8709360, 380))
    CONTROLLER_VTABLE = 40568232
    OBSERVER_PAWN_VTABLE = 40030904
    PLAYER_PAWN_VTABLE = 40082848
    FAMILIAR_CLONE_PAWN_VTABLE = 41838848
    SERVICES_VTABLES = (40570864, 44376968)
    CONTROLLER_FINAL_VTABLE = 40568184
    OBSERVER_SERVICES_OFFSET = 3736
    ENTITY_LIST = 54681528
    CONTROLLER = 62721712
    OBSERVER_PREDICATE = 5425312
    GET_OBSERVER_MODE = 8800976
    GET_OBSERVER_TARGET = 8800992
    PLAYER_PREDICATE = 23008064
    PLAYER_DATA_PREDICATE = 5799584
    CONTROLLER_PREDICATE = 7380080
    IDENTITY_STRIDE = 112
    IDENTITY_HANDLE = 16
    ENTITY_IDENTITY = 16
    CONTROLLER_PAWN = 1724
    NETWORK_STATE = 1007
    OBSERVER_PREDICATE_SLOT = 1280
    OBSERVER_MODE_SLOT = 240
    OBSERVER_TARGET_SLOT = 256
    OBSERVER_MODE = 72
    OBSERVER_TARGET = 76
    PLAYER_PREDICATE_SLOT = 1248
    PLAYER_DATA_PREDICATE_SLOT = 2776
    PAWN_CONTROLLER = 1308
    CONTROLLER_PREDICATE_SLOT = 1256
    CONTROLLER_FINAL_DATA = 2312


class AttachRuntime:
    CLIENT_SHA256 = '948260612c9b7243964e4a0d5f0f6252ae846ceaa6e8c0e95b83bd5eba4caf60'
    CLIENT_IMAGE_SIZE = 68485120
    INITIALIZER = 33757248
    ENTITY_VTABLE = 44305904
    ENTITY_GLOBAL = 64301616
    INITIALIZER_BYTES = b'\x0f\xb6D$(\x88D$(H\x89\r\xe0\x11\xd2\x01\xe9\x9b\xbf\xff\xff'


ATTACH_FIELD_SPECS = (('player_origin', 'CGameSceneNode', 'm_vecAbsOrigin', 'VectorWS', True), ('player_angles', 'CGameSceneNode', 'm_angAbsRotation', 'QAngle', True), ('eye_offset', 'C_BaseModelEntity', 'm_vecViewOffset', 'CNetworkViewOffsetVector', True), ('eye_angles', 'C_CitadelPlayerPawn', 'm_angEyeAngles', 'QAngle', True), ('scene_child', 'CGameSceneNode', 'm_pChild', 'CGameSceneNode*', True), ('scene_sibling', 'CGameSceneNode', 'm_pNextSibling', 'CGameSceneNode*', True), ('world_transform', 'CGameSceneNode', 'm_nodeToWorld', 'CTransformWS', False), ('attach_bone', 'CGameSceneNode', 'm_nParentAttachmentOrBone', 'int16', False), ('owner_entity', 'C_BaseEntity', 'm_hOwnerEntity', 'CHandle', False), ('pawn_controller', 'C_BasePlayerPawn', 'm_hController', 'CHandle', False))
ATTACH_WIRE_FIELDS = ('scene_node', 'owner', 'player_origin', 'player_angles', 'eye_offset', 'eye_angles', 'scene_child', 'scene_sibling')
VIEW_OFFSET_VALUE_OFFSETS = (16, 24, 32)
