// Generated by tools/generate_ui_tokens.py from dolly/ui_theme.py.
// Do not edit by hand; change dolly/ui_theme.py and re-run the generator.
#pragma once

namespace dolly::ui {

constexpr unsigned ACCENT = 0x8ec6ba;
constexpr unsigned ACCENT_ACTIVE = 0x74a89e;
constexpr unsigned ACCENT_HOVER = 0xa6d6cd;
constexpr unsigned ACCENT_INK = 0x0c1a18;
constexpr unsigned BG = 0x12161a;
constexpr unsigned BUTTON = 0x27313a;
constexpr unsigned BUTTON_ACTIVE = 0x2c3a3e;
constexpr unsigned BUTTON_HOVER = 0x35424c;
constexpr unsigned DANGER = 0xcf8c80;
constexpr unsigned DISABLED_BG = 0x1b232a;
constexpr unsigned DISABLED_FG = 0x66747e;
constexpr unsigned EDGE = 0x2b343b;
constexpr unsigned FIELD = 0x0f1317;
constexpr unsigned KEYCAP = 0xa2adb4;
constexpr unsigned KEYCAP_INK = 0x12161a;
constexpr unsigned MUTED = 0xa2adb4;
constexpr unsigned PANEL = 0x1b2126;
constexpr unsigned PANEL_ALT = 0x232a30;
constexpr unsigned SCROLL_HOVER = 0x43525c;
constexpr unsigned SELECTED = 0x2b403f;
constexpr unsigned SELECTED_INK = 0xdff0ed;
constexpr unsigned STRONG = 0xe6ecee;
constexpr unsigned TAB_DIM = 0x181d21;
constexpr unsigned TAB_DIM_OVERLINE = 0x3d5f5a;
constexpr unsigned TAB_DIM_SELECTED = 0x243033;
constexpr unsigned TEXT = 0xd2d8db;
constexpr unsigned TRACK = 0x27313a;
constexpr unsigned WARN = 0xd9bd76;
constexpr unsigned WARN_BG = 0x332f22;

}  // namespace dolly::ui
