"""Generate the native UI token header from :mod:`dolly.ui_theme`.

Keeps the in-game ImGui panel and the desktop Tk surfaces on one palette. Run
after any change to ``dolly/ui_theme.py``::

    python tools/generate_ui_tokens.py            # write the header
    python tools/generate_ui_tokens.py --check     # verify it is current

``tests/test_ui_theme.py`` runs the ``--check`` path, so a stale header fails the
suite.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dolly import ui_theme  # noqa: E402  (path setup precedes the import)

HEADER = ROOT / "native" / "src" / "dolly_ui_tokens_generated.hpp"


def render() -> str:
    lines = [
        "// Generated by tools/generate_ui_tokens.py from dolly/ui_theme.py.",
        "// Do not edit by hand; change dolly/ui_theme.py and re-run the generator.",
        "#pragma once",
        "",
        "namespace dolly::ui {",
        "",
    ]
    for name in sorted(ui_theme.TOKENS):
        value = ui_theme.TOKENS[name]
        ui_theme.rgb(value)  # validate before emitting
        lines.append(f"constexpr unsigned {name.upper()} = 0x{value.lstrip('#')};")
    lines += ["", "}  // namespace dolly::ui", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Fail if the checked-in header is not current.")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        actual = HEADER.read_text(encoding="utf-8") if HEADER.is_file() else ""
        if actual != expected:
            print(f"{HEADER} is out of date; run tools/generate_ui_tokens.py", file=sys.stderr)
            return 1
        return 0
    HEADER.write_text(expected, encoding="utf-8")
    print(f"Wrote {HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
